{% set version = "0.5.1" %}

package:
  name: torchdata
  version: {{ version }}

source:
  url: https://github.com/pytorch/data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 69d80bd33ce8f08e7cfeeb71cefddfc29cede25a85881e33dbae47576b96ed29

build:
  number: 0
  skip: true  # [py<37]
  skip: true  # [win or s390x]
  skip: true  # [ppc64le and py>=311]
  script:
    - export USE_SYSTEM_LIBS=TRUE
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - pip
    - python
    - pybind11
    - pytorch
    - setuptools
    - wheel
  run:
    - python
    - requests
    - urllib3 >=1.25
    - portalocker >=2.0.0
    - pytorch

test:
  imports:
    - torchdata
  requires:
    - pip
    - pytest
    - datasets
    - expecttest
    - fsspec
    - numpy
    - s3fs
  source_files:
    - test/

about:
  home: https://github.com/pytorch/data
  summary: A PyTorch repo for data loading and utilities to be shared by the PyTorch domain libraries.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
    - Tobias-Fischer
    - h-vetinari
