{% set version = "0.5.1" %}

package:
  name: torchdata
  version: {{ version }}

source:
  url: https://github.com/pytorch/data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 69d80bd33ce8f08e7cfeeb71cefddfc29cede25a85881e33dbae47576b96ed29

build:
  number: 1
  # no pytorch on windows in conda-forge, see
  # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32
  skip: true  # [win]
  script:
    - export BUILD_S3=TRUE
    - export CMAKE_GENERATOR="Ninja"
    - export USE_SYSTEM_LIBS=TRUE
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - pip
    - python
    - pybind11
    - aws-sdk-cpp
    - pytorch
  run:
    - python
    - requests
    - urllib3 >=1.25
    - portalocker >=2.0.0
    - pytorch

test:
  imports:
    - torchdata
  requires:
    - pip
    - pytest
    - adlfs
    - datasets
    - expecttest
    - fsspec
    - numpy *
    - s3fs
  source_files:
    - test/
  commands:
    - pip check
    # test_audio_examples uses an uninstalled local folder ("examples");
    # avoid test_text_examples due to cycle since torchtext depends on torchdata
    - pytest test/ -v --ignore=test/test_audio_examples.py --ignore=test/test_text_examples.py

about:
  home: https://github.com/pytorch/data
  summary: A PyTorch repo for data loading and utilities to be shared by the PyTorch domain libraries.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
    - Tobias-Fischer
